# Generated by Django 2.2.6 on 2019-10-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMecanico', models.CharField(max_length=50)),
                ('especializacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreModelo', models.CharField(max_length=30)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRespuesto', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('tipoUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=9)),
                ('year', models.DateField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReserva', models.CharField(max_length=50)),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('descripcion', models.CharField(max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTrabajo', models.CharField(max_length=50)),
                ('fechaComienzo', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('abono', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Cliente')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Mecanico')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Repuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.Vehiculo')),
            ],
        ),
    ]
